### ISSUE TITLE
Empty includes should probably be dropped

### ISSUE THREAD

**Issue by lpw25** [ocaml/odoc#725]
If you look at [the base docs on v3](https://v3.ocaml.org/p/base/v0.14.1/doc/Base/Int64/index.html) the very first include is empty because all its contents have been shadowed by later definitions. In such cases the include should probably just be removed.

**Comment by asavahista** [comment]
i think there are a few alternatives:
- showing shadowed definitions, with formatting to show they are shadowed
- having less nested includes take precedence. the more nested ones could link back (or forward) to the top level one
  - (this would address includes of the same module multiple times, as is the case here, rather than actual shadowing, so this issue may still be valid even if this is done)
- if it really *should* be removed, maybe this can be ignored - it could be a linter warning if it isn't already
- or just proceed with this.

**Comment by Julow** [comment]
This has been solved in https://github.com/ocaml/odoc/pull/798 so can be closed.

I like the idea of still showing the shadowed definitions, styled differently but this might be a bit hard to implement currently because OCaml drops some shadowed definitions and Odoc's internal representation drops the others. This can work only for includes.

Shadowed includes are actually generated and only hidden using CSS. Here's how they can be rendered greyed:

```css
.odoc-include.shadowed-include {
  display: block;
}
.odoc-include.shadowed-include .spec {
  background: #eee;
  border-left-color: #ccc;
  color: #888;
}
```
