### ISSUE TITLE
CSS regression: large margin in mobile mode makes content unreadable

### ISSUE THREAD

**Issue by sanette** [ocaml/odoc#838]
"recently" (odoc 2.0.2, odoc 2.1.0)
html pages viewed in mobile mode keep the very large margin of the desktop mode and hence become unreadable, see screenshot:
![Screenshot_20220225_235043](https://user-images.githubusercontent.com/7536536/155813654-cd2a8018-8aa8-40fc-932c-9e5072c9ec3e.png)

**Comment by sanette** [comment]
This can be "solved" by adding to `odoc.css`
```css
@media only screen and (max-width: 95ex) {
 body {
	margin: 2ex;
    }
}
```
but I didn't study the file closely enough to be sure this the best solution.
