### ISSUE TITLE
Make alerts visually stand out

### ISSUE THREAD

**Issue by yawaramin** [ocaml/odoc#925]
I propose to prefix rendered alerts with the ⚠️ emoji to make them visually stand out a bit more. It would be a nice quality-of-life improvement in my opinion. E.g.

> ⚠️ Alert unsafe This function could launch ze missiles.

It is _almost_ but not quite doable with the current HTML:

```html
<span class="at-tag">alert</span>
```

If we added a class `ocaml-alert` to the `span`, we could easily do the icon with a tiny bit of CSS:

```css
.ocaml-alert::before {
  content: '⚠️ ';
}
```

**Comment by dbuenzli** [comment]
We should simply add the tag as a class to for any tag.

**Comment by panglesd** [comment]
One level above the `at-tag` element already lies the tag added as a class:
```html
<li class="alert">
  <span class="at-tag">Alert</span>
  unsafe This function could launch ze missiles.
</li>
```

For this specific use case, this rule would work:
```css
.alert::before {
  content: '⚠️ ';
}
```
But to apply the css rule exclusively to the "Alert" element, as requested originally, you can use:
```css
.alert > .at-tag::before {
  content: '⚠️ ';
}
```

About actually adding the css rule to the output generated by `odoc`, I don't know! But maybe more "specialized" output, such as ocaml.org, would know more.
